apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: mginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: tier
                    operator: In
                    values:
                    - gold
      containers:
      - name: nginx
        image: nginx