apiVersion: v1
kind: Pod
metadata:
  name: myvolemptydir
spec:
  containers:
  - name: c1
    image: centos
    command:
      - sleep
      - "15000"
    volumeMounts:
    - name: xchange
      mountPath: "/tmp/xchange"
  - name: c2
    image: centos
    command:
      - sleep
      - "15000"
    volumeMounts:
    - name: xchange
      mountPath: "/tmp/data"
  volumes:
  - name: xchange
    emptyDir: {}
